name: bazaar
description: "A dynamic Flipkart-inspired e-commerce app built with Flutter and Riverpod, showcasing a clean architecture, beautiful Material 3 design, and a seamless, responsive user experience, all ready to connect with Firebase."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  cached_network_image: ^3.0.0
  intl: 0.20.2
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^5.0.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.5.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  cloud_firestore: ^6.1.0
  riverpod_annotation: ^3.0.3
  collection: ^1.18.0
  font_awesome_flutter: ^10.7.0
  uuid: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.6
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/ # Add your Lottie animation files here, e.g., order_success.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
